# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
#
# Settings in the readthedocs online dashboard will be ignored.

# Required
version: 2

# Build documentation in the doc/main directory with Sphinx
sphinx:
   configuration: doc/main/conf.py

# Build your docs in additional formats such as PDF
formats:
   - pdf

# Set the version of Python and requirements required to build the docs
python:
   version: 3.8
   install:
   - requirements: rtd-requirements.txt
